### ISSUE TITLE
`Failed to initialize Storj environment` when uploading many files simultaneously 

### ISSUE THREAD

**Issue by MeijeSibbel** [kaloyan-raev/hello-storj#10]
I tried uploading 15 files at the same time but i get a `Failed to initialize Storj environment ` on some uploads

**Comment by kaloyan-raev** [comment]
This error happens when the call to the native storj_init_env() function is not successful. Most probably some memory allocation failed.

/cc @braydonf

**Comment by kaloyan-raev** [comment]
This should be resolved with the latest v0.8. The Storj environment is now reused between calls, instead of creating new one for each call to bridge.
