### ISSUE TITLE
Registration Java API

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#16]
Please expose the method in the native library to allow for registration of new users

**Comment by kaloyan-raev** [comment]
@dri94 Now you have the `Storj.register()` Java method for the bridge account registration. I also implemented some simple UI for testing it - see the Register action in the main activity.

The workflow in the app for new users should be like this:
1. Ask the user for email and password to register a new account
1. Call `Storj.register()` with the email and password
1. Upon success ask the user to check her inbox for a registration mail and click the confirmation link
1. Call `Storj.generateMnemonic()` to generate new encryption key
1. Display the generated encryption key to the user and ask her to write it down on a list of paper for backup
1. Call `Storj.importKeys()` with the email, password and encryption key to create the authentication file on the device

That's it! Good luck :)
