### ISSUE TITLE
public static native void setCAInfoPath(String path); not found

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#17]
Updating to Fix 16 i am getting the error public static native void setCAInfoPath(String path); not defined. This could be an error on my part. However i cannot be sure until i know where this method is, as i cannot find it in the native-lib

**Comment by kaloyan-raev** [comment]
This method was removed with commit https://github.com/kaloyan-raev/hello-storj/commit/ffcd35f75441abba6c01431e0fa07f690c2fbf63

Instead of calling the method now you should set an env var. Check the changes in the App class.
