### ISSUE TITLE
Remove mnemonic requirement

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#21]
The mnemonic is required in the Keys class. While the security is great, this also makes it so you can only read buckets created with the app, and not online. You should make the mnemonic optional.

**Comment by kaloyan-raev** [comment]
The mnemonic is required by the libstorj library and is fundamental part of Storj encryption. If when you say "online" means the Bridge Web GUI then it is currently a limitation in the Bridge Web GUI that you cannot enter the mnemonic and decrypt buckets. See https://github.com/Storj/bridge-gui/issues/137
