### ISSUE TITLE
Allow for bucket/key association

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#23]
Allow for multiple keys to be imported, and for them to have association to specific buckets. Key-Hello is associated with Bucket1. So you can have all your buckets decrypted

**Comment by kaloyan-raev** [comment]
Currently the libstorj native library uses an authentication file with one encryption key (mnemonic) per bridge account. While it is technically possible to create multiple authentication files for the same account, I am not sure if it is practical to use multiple mnemonics for the same account. This would also complicate the workflow for creating new buckets and uploading files - the user should select which of the several mnemonics to be used in each case.

@braydonf what do you think about this?

**Comment by braydonf** [comment]
I agree it would complicate the workflow.

There is an authentication code and hmac when decrypting to check for success -- that the correct key is being used and the file is as expected. For example buckets and files that fail this check can be displayed as "unavailable/undecryptable". 

Multiple accounts would likely be the best approach.

**Comment by kaloyan-raev** [comment]
I am closing this one. I opened #27 for the multiple accounts support.
