### ISSUE TITLE
Why are document provider uploads not supported?

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#24]
I'm sure you have a reason, but just curious as to why document provider uploads are not supported?

**Comment by kaloyan-raev** [comment]
It's correct to say that _some_ document providers are not supported. The list of supported document providers can be seen in the [FileUtils](https://github.com/kaloyan-raev/hello-storj/blob/master/app/src/main/java/name/raev/kaloyan/hellostorj/utils/FileUtils.java) class. This class should be improved to support more document providers.

Also, if a document provider represents a remote storage then the file should be first downloaded from this remote location before uploading to the Storj network.
