### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#29]
I am getting this error when trying to upload a jpg file. This is directly using the sample app here

09-29 08:49:49.664 9471-9733/name.raev.kaloyan.hellostorj.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9733 (Thread-7)
09-29 08:49:49.708 9757-9757/? A/DEBUG: pid: 9471, tid: 9733, name: Thread-7  >>> name.raev.kaloyan.hellostorj.debug <<<
09-29 08:49:49.709 9757-9757/? A/DEBUG:     #00 pc 00075c38  /data/app/name.raev.kaloyan.hellostorj.debug-U_qNbuYEo4Rl6uEZWS5h0Q==/lib/arm/libnative-lib.so
09-29 08:49:49.709 9757-9757/? A/DEBUG:     #01 pc 001e11c4  /data/app/name.raev.kaloyan.hellostorj.debug-U_qNbuYEo4Rl6uEZWS5h0Q==/lib/arm/libnative-lib.so

**Comment by kaloyan-raev** [comment]
Thanks for reporting!

It seems to be a regression compared to the latest official release (0.6.1). I will fix it ASAP.
