### ISSUE TITLE
Detailed error messages

### ISSUE THREAD

**Issue by dri94** [kaloyan-raev/hello-storj#31]
When receiving an error message on upload all that is returned is the filepath (or in some cases, just null). However this does not tell us why it failed. This can be very important for the message shown to the user, and for simply developer debugging in the app. Giving the error message that the JNI received back to the callback will be an extremely useful feature.

**Comment by kaloyan-raev** [comment]
Error messages are provided for uploads. For example, if you try uploading a file that already exists in the bucket then you will get "Upload failed. File already exists (1013)".

Perhaps, you are hitting some corner case. Could provide exact steps to reproduce?

**Comment by dri94** [comment]
It would literally just come through as null. But i get error messages now. Unsure what was happening
